name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew :composeApp:wasmJsBrowserProductionExecutableDistribution

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: composeApp/build/dist/wasmJs/productionExecutable
          branch: gh-pages